# Generated by Django 2.0.1 on 2018-09-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=250)),
                ('list_id', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=250)),
            ],
        ),
    ]
