# Generated by Django 2.0.1 on 2018-03-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0007_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(to='core.Topic'),
        ),
    ]
