# Generated by Django 2.0.1 on 2018-04-10 16:22

from django.db import migrations, models
import wac.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='file',
            field=models.FileField(storage=wac.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
