# Generated by Django 2.0.1 on 2018-06-28 14:28

from django.db import migrations, models
import wac.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180628_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='file',
            field=models.ImageField(max_length=200, storage=wac.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
