# Generated by Django 2.0.1 on 2018-06-28 14:58

from django.db import migrations
import django_resized.forms
import wac.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180628_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, max_length=200, quality=0, size=[200, 200], storage=wac.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
