# Generated by Django 2.0.1 on 2018-08-20 20:42

from django.db import migrations, models
import django_resized.forms
import wac.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180628_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, max_length=200, quality=99, size=[250, 250], storage=wac.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
