# Generated by Django 2.0.1 on 2018-08-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180820_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_mailing_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='speaker_mailing_list',
            field=models.BooleanField(default=False),
        ),
    ]
