# Generated by Django 2.0.1 on 2018-08-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180826_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='speaker_mailing_list',
            field=models.BooleanField(default=True),
        ),
    ]
