# Generated by Django 2.0.1 on 2018-08-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180828_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newsletter_mailing_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='speaker_mailing_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='mc_groups',
            field=models.TextField(default='{}'),
        ),
    ]
