# Generated by Django 2.0.1 on 2018-09-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180907_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mc_groups',
        ),
    ]
