# Generated by Django 2.0.2 on 2018-11-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_profile_lgtbqa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lgtbqa',
            new_name='lgbtqa',
        ),
    ]
