# Generated by Django 2.0.1 on 2018-03-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_of_conduct', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(max_length=250)),
                ('event_date', models.DateField()),
                ('event_name', models.CharField(blank=True, max_length=250, null=True)),
                ('event_time', models.TimeField()),
                ('full_name', models.CharField(max_length=250)),
                ('speaker_compensation', models.BooleanField(default=False)),
                ('venue_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
