# Generated by Django 2.0.1 on 2018-03-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_speaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
